
class Lexemes:
    AND = "and"
    ASSIGN = "="
    CLASS = "class"
    COLON = ":"
    COMMA = ","
    DEF = "def"
    DIFF = "-"
    DIV_FLOAT = "/"
    DIV_INT = "//"
    EQ = "=="
    ELIF = "elif"
    ELSE = "else"
    EOL_COMMENT = "#"
    FOR = "for"
    GLOBAL = "global"
    GE = ">="
    GT = ">"
    IF = "if"
    IN = "in"
    LE = "<="
    LPAREN = "("
    LT = "<"
    ML_COMMENT = '"""'
    MOD = "%"
    MULT = "*"
    NE = "!="
    NONLOCAL = "nonlocal"
    NOT = "not"
    OR = "or"
    PASS = "pass"
    QUOTE = ' " '
    RPAREN = ")"
    RETURN = "return"
    SUM = "+"
    WHILE = "while"